name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Suggest a new feature for Project Collaborans!

  - type: textarea
    id: feature
    attributes:
      label: Feature description
      description: What feature would you like to see?
      placeholder: "It would be helpful if..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      description: What problem would this feature address?
      placeholder: "Currently it's difficult to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you envision this working?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered other approaches?
    validations:
      required: false
